version: '3'
services:
  db-app:
    container_name: db-app
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    networks:
      - docker-kubernetes
    environment:
      MYSQL_DATABASE: msvc_app
      MYSQL_USER: Juanem
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data-mysql:/var/lib/mysql

  msvc-cursos:
    container_name: msvc-cursos
    image: juanemar/cursos
    #build:
    #  context: ./
    #  dockerfile: ./msvc-cursos/Dockerfile
    restart: always
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: db-app:3306
      DB_DATABASE: msvc_app
      DB_USERNAME: Juanem
      DB_PASSWORD: root
      USUARIOS_URL: msvc-usuarios:8001
    networks:
      - docker-kubernetes
    depends_on:
      - db-app
      - msvc-usuarios

  msvc-usuarios:
    container_name: msvc-usuarios
    image: juanemar/usuarios
    #build:
    #  context: ./
    #  dockerfile: ./msvc-usuarios/Dockerfile
    restart: always
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: db-app:3306
      DB_DATABASE: msvc_app
      DB_USERNAME: Juanem
      DB_PASSWORD: root
      CURSOS_URL: msvc-cursos:8002
    networks:
      - docker-kubernetes
    depends_on:
      - db-app

networks:
  docker-kubernetes:
    driver: bridge

volumes:
  data-mysql: