version: '3'
services:
  db-app:
    container_name: db-app
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    networks:
      - docker-kubernetes
    environment:
      MYSQL_DATABASE: msvc_app
      MYSQL_USER: Juanem
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data-mysql:/var/lib/mysql

  msvc-cursos:
    container_name: msvc-cursos
    #image: cursos
    build:
      context: ./
      dockerfile: ./msvc-cursos/Dockerfile
    restart: always
    ports:
      - "8002:8002"
    env_file:
      - ./msvc-cursos/.env
    networks:
      - docker-kubernetes
    depends_on:
      - db-app
      - msvc-usuarios

  msvc-usuarios:
    container_name: msvc-usuarios
    #image: usuarios
    build:
      context: ./
      dockerfile: ./msvc-usuarios/Dockerfile
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - ./msvc-usuarios/.env
    networks:
      - docker-kubernetes
    depends_on:
      - db-app

networks:
  docker-kubernetes:
    driver: bridge

volumes:
  data-mysql: